apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-postgres-pvc
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  {{- if .Values.database.persistence.storageClass }}
  storageClassName: {{ .Values.database.persistence.storageClass }}
  {{- end }}