apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-postgres-secret
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.database.credentials.password | b64enc | quote }}
  postgres-username: {{ .Values.database.credentials.username | b64enc | quote }}
  postgres-db: {{ .Values.database.credentials.database | b64enc | quote }}