{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-network-policy
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "todo-chatbot.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{- range .Values.networkPolicy.allowFrom }}
      - {{ . | toYaml | nindent 8 }}
      {{- end }}
      ports:
      - protocol: TCP
        port: 8000
      - protocol: TCP
        port: 3000
      - protocol: TCP
        port: 5432
{{- end }}