apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-evolution.fullname" . }}-audit
spec:
  type: {{ .Values.services.audit.type }}
  ports:
  - port: {{ .Values.services.audit.port }}
    targetPort: {{ .Values.services.audit.port }}
    name: http
  selector:
    app: audit