apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-evolution.fullname" . }}-frontend
spec:
  type: {{ .Values.services.frontend.type }}
  ports:
  - port: {{ .Values.services.frontend.port }}
    targetPort: {{ .Values.services.frontend.port }}
    name: http
  selector:
    app: frontend